export const countries = [
    { code: "AD", name: "Andorra", phone: "+376", flag: "andorra.svg" },
    { code: "AE", name: "United Arab Emirates", phone: "+971", flag: "uae.svg" },
    { code: "AF", name: "Afghanistan", phone: "+93", flag: "afghanistan.svg" },
    { code: "AG", name: "Antigua and Barbuda", phone: "+1268", flag: "antigua.svg" },
    { code: "AI", name: "Anguilla", phone: "+1264", flag: "anguilla.svg" },
    { code: "AL", name: "Albania", phone: "+355", flag: "albania.svg" },
    { code: "AM", name: "Armenia", phone: "+374", flag: "armenia.svg" },
    { code: "AO", name: "Angola", phone: "+244", flag: "angola.svg" },
    { code: "AR", name: "Argentina", phone: "+54", flag: "argentina.svg" },
    { code: "AS", name: "American Samoa", phone: "+1684", flag: "american-samoa.svg" },
    { code: "AT", name: "Austria", phone: "+43", flag: "austria.svg" },
    { code: "AU", name: "Australia", phone: "+61", flag: "australia.svg" },
    { code: "AW", name: "Aruba", phone: "+297", flag: "aruba.svg" },
    { code: "AZ", name: "Azerbaijan", phone: "+994", flag: "azerbaijan.svg" },
    { code: "BA", name: "Bosnia and Herzegovina", phone: "+387", flag: "bosnia.svg" },
    { code: "BB", name: "Barbados", phone: "+1246", flag: "barbados.svg" },
    { code: "BD", name: "Bangladesh", phone: "+880", flag: "bangladesh.svg" },
    { code: "BE", name: "Belgium", phone: "+32", flag: "belgium.svg" },
    { code: "BF", name: "Burkina Faso", phone: "+226", flag: "burkina-faso.svg" },
    { code: "BG", name: "Bulgaria", phone: "+359", flag: "bulgaria.svg" },
    { code: "BH", name: "Bahrain", phone: "+973", flag: "bahrain.svg" },
    { code: "BI", name: "Burundi", phone: "+257", flag: "burundi.svg" },
    { code: "BJ", name: "Benin", phone: "+229", flag: "benin.svg" },
    { code: "BM", name: "Bermuda", phone: "+1441", flag: "bermuda.svg" },
    { code: "BN", name: "Brunei", phone: "+673", flag: "brunei.svg" },
    { code: "BO", name: "Bolivia", phone: "+591", flag: "bolivia.svg" },
    { code: "BR", name: "Brazil", phone: "+55", flag: "brazil.svg" },
    { code: "BS", name: "Bahamas", phone: "+1242", flag: "bahamas.svg" },
    { code: "BT", name: "Bhutan", phone: "+975", flag: "bhutan.svg" },
    { code: "BW", name: "Botswana", phone: "+267", flag: "botswana.svg" },
    { code: "BY", name: "Belarus", phone: "+375", flag: "belarus.svg" },
    { code: "BZ", name: "Belize", phone: "+501", flag: "belize.svg" },
    { code: "CA", name: "Canada", phone: "+1", flag: "canada.svg" },
    { code: "CD", name: "Congo (DRC)", phone: "+243", flag: "congo-drc.svg" },
    { code: "CF", name: "Central African Republic", phone: "+236", flag: "central-african-republic.svg" },
    { code: "CG", name: "Congo", phone: "+242", flag: "congo.svg" },
    { code: "CH", name: "Switzerland", phone: "+41", flag: "switzerland.svg" },
    { code: "CI", name: "Côte d'Ivoire", phone: "+225", flag: "ivory-coast.svg" },
    { code: "CK", name: "Cook Islands", phone: "+682", flag: "cook-islands.svg" },
    { code: "CL", name: "Chile", phone: "+56", flag: "chile.svg" },
    { code: "CM", name: "Cameroon", phone: "+237", flag: "cameroon.svg" },
    { code: "CN", name: "China", phone: "+86", flag: "china.svg" },
    { code: "CO", name: "Colombia", phone: "+57", flag: "colombia.svg" },
    { code: "CR", name: "Costa Rica", phone: "+506", flag: "costa-rica.svg" },
    { code: "CU", name: "Cuba", phone: "+53", flag: "cuba.svg" },
    { code: "CV", name: "Cape Verde", phone: "+238", flag: "cape-verde.svg" },
    { code: "CY", name: "Cyprus", phone: "+357", flag: "cyprus.svg" },
    { code: "CZ", name: "Czech Republic", phone: "+420", flag: "czech-republic.svg" },
    { code: "DE", name: "Germany", phone: "+49", flag: "germany.svg" },
    { code: "DJ", name: "Djibouti", phone: "+253", flag: "djibouti.svg" },
    { code: "DK", name: "Denmark", phone: "+45", flag: "denmark.svg" },
    { code: "DM", name: "Dominica", phone: "+1767", flag: "dominica.svg" },
    { code: "DO", name: "Dominican Republic", phone: "+1809", flag: "dominican-republic.svg" },
    { code: "DZ", name: "Algeria", phone: "+213", flag: "algeria.svg" },
    { code: "EC", name: "Ecuador", phone: "+593", flag: "ecuador.svg" },
    { code: "EE", name: "Estonia", phone: "+372", flag: "estonia.svg" },
    { code: "EG", name: "Egypt", phone: "+20", flag: "egypt.svg" },
    { code: "ER", name: "Eritrea", phone: "+291", flag: "eritrea.svg" },
    { code: "ES", name: "Spain", phone: "+34", flag: "spain.svg" },
    { code: "ET", name: "Ethiopia", phone: "+251", flag: "ethiopia.svg" },
    { code: "FI", name: "Finland", phone: "+358", flag: "finland.svg" },
    { code: "FJ", name: "Fiji", phone: "+679", flag: "fiji.svg" },
    { code: "FK", name: "Falkland Islands", phone: "+500", flag: "falkland-islands.svg" },
    { code: "FM", name: "Micronesia", phone: "+691", flag: "micronesia.svg" },
    { code: "FO", name: "Faroe Islands", phone: "+298", flag: "faroe-islands.svg" },
    { code: "FR", name: "France", phone: "+33", flag: "france.svg" },
    { code: "GA", name: "Gabon", phone: "+241", flag: "gabon.svg" },
    { code: "GB", name: "United Kingdom", phone: "+44", flag: "uk.svg" },
    { code: "GD", name: "Grenada", phone: "+1473", flag: "grenada.svg" },
    { code: "GE", name: "Georgia", phone: "+995", flag: "georgia.svg" },
    { code: "GF", name: "French Guiana", phone: "+594", flag: "french-guiana.svg" },
    { code: "GH", name: "Ghana", phone: "+233", flag: "ghana.svg" },
    { code: "GI", name: "Gibraltar", phone: "+350", flag: "gibraltar.svg" },
    { code: "GL", name: "Greenland", phone: "+299", flag: "greenland.svg" },
    { code: "GM", name: "Gambia", phone: "+220", flag: "gambia.svg" },
    { code: "GN", name: "Guinea", phone: "+224", flag: "guinea.svg" },
    { code: "GP", name: "Guadeloupe", phone: "+590", flag: "guadeloupe.svg" },
    { code: "GQ", name: "Equatorial Guinea", phone: "+240", flag: "equatorial-guinea.svg" },
    { code: "GR", name: "Greece", phone: "+30", flag: "greece.svg" },
    { code: "GT", name: "Guatemala", phone: "+502", flag: "guatemala.svg" },
    { code: "GU", name: "Guam", phone: "+1671", flag: "guam.svg" },
    { code: "GW", name: "Guinea-Bissau", phone: "+245", flag: "guinea-bissau.svg" },
    { code: "GY", name: "Guyana", phone: "+592", flag: "guyana.svg" },
    { code: "HK", name: "Hong Kong", phone: "+852", flag: "hong-kong.svg" },
    { code: "HN", name: "Honduras", phone: "+504", flag: "honduras.svg" },
    { code: "HR", name: "Croatia", phone: "+385", flag: "croatia.svg" },
    { code: "HT", name: "Haiti", phone: "+509", flag: "haiti.svg" },
    { code: "HU", name: "Hungary", phone: "+36", flag: "hungary.svg" },
    { code: "ID", name: "Indonesia", phone: "+62", flag: "indonesia.svg" },
    { code: "IE", name: "Ireland", phone: "+353", flag: "ireland.svg" },
    { code: "IL", name: "Israel", phone: "+972", flag: "israel.svg" },
    { code: "IN", name: "India", phone: "+91", flag: "india.svg" },
    { code: "IO", name: "British Indian Ocean Territory", phone: "+246", flag: "british-indian-ocean.svg" },
    { code: "IQ", name: "Iraq", phone: "+964", flag: "iraq.svg" },
    { code: "IR", name: "Iran", phone: "+98", flag: "iran.svg" },
    { code: "IS", name: "Iceland", phone: "+354", flag: "iceland.svg" },
    { code: "IT", name: "Italy", phone: "+39", flag: "italy.svg" },
    { code: "JM", name: "Jamaica", phone: "+1876", flag: "jamaica.svg" },
    { code: "JO", name: "Jordan", phone: "+962", flag: "jordan.svg" },
    { code: "JP", name: "Japan", phone: "+81", flag: "japan.svg" },
    { code: "KE", name: "Kenya", phone: "+254", flag: "kenya.svg" },
    { code: "KG", name: "Kyrgyzstan", phone: "+996", flag: "kyrgyzstan.svg" },
    { code: "KH", name: "Cambodia", phone: "+855", flag: "cambodia.svg" },
    { code: "KI", name: "Kiribati", phone: "+686", flag: "kiribati.svg" },
    { code: "KM", name: "Comoros", phone: "+269", flag: "comoros.svg" },
    { code: "KN", name: "Saint Kitts and Nevis", phone: "+1869", flag: "saint-kitts-nevis.svg" },
    { code: "KP", name: "North Korea", phone: "+850", flag: "north-korea.svg" },
    { code: "KR", name: "South Korea", phone: "+82", flag: "south-korea.svg" },
    { code: "KW", name: "Kuwait", phone: "+965", flag: "kuwait.svg" },
    { code: "KY", name: "Cayman Islands", phone: "+1345", flag: "cayman-islands.svg" },
    { code: "KZ", name: "Kazakhstan", phone: "+7", flag: "kazakhstan.svg" },
    { code: "LA", name: "Laos", phone: "+856", flag: "laos.svg" },
    { code: "LB", name: "Lebanon", phone: "+961", flag: "lebanon.svg" },
    { code: "LC", name: "Saint Lucia", phone: "+1758", flag: "saint-lucia.svg" },
    { code: "LI", name: "Liechtenstein", phone: "+423", flag: "liechtenstein.svg" },
    { code: "LK", name: "Sri Lanka", phone: "+94", flag: "sri-lanka.svg" },
    { code: "LR", name: "Liberia", phone: "+231", flag: "liberia.svg" },
    { code: "LS", name: "Lesotho", phone: "+266", flag: "lesotho.svg" },
    { code: "LT", name: "Lithuania", phone: "+370", flag: "lithuania.svg" },
    { code: "LU", name: "Luxembourg", phone: "+352", flag: "luxembourg.svg" },
    { code: "LV", name: "Latvia", phone: "+371", flag: "latvia.svg" },
    { code: "LY", name: "Libya", phone: "+218", flag: "libya.svg" },
    { code: "MA", name: "Morocco", phone: "+212", flag: "morocco.svg" },
    { code: "MC", name: "Monaco", phone: "+377", flag: "monaco.svg" },
    { code: "MD", name: "Moldova", phone: "+373", flag: "moldova.svg" },
    { code: "ME", name: "Montenegro", phone: "+382", flag: "montenegro.svg" },
    { code: "MG", name: "Madagascar", phone: "+261", flag: "madagascar.svg" },
    { code: "MH", name: "Marshall Islands", phone: "+692", flag: "marshall-islands.svg" },
    { code: "MK", name: "North Macedonia", phone: "+389", flag: "north-macedonia.svg" },
    { code: "ML", name: "Mali", phone: "+223", flag: "mali.svg" },
    { code: "MM", name: "Myanmar", phone: "+95", flag: "myanmar.svg" },
    { code: "MN", name: "Mongolia", phone: "+976", flag: "mongolia.svg" },
    { code: "MO", name: "Macau", phone: "+853", flag: "macau.svg" },
    { code: "MP", name: "Northern Mariana Islands", phone: "+1670", flag: "northern-mariana.svg" },
    { code: "MQ", name: "Martinique", phone: "+596", flag: "martinique.svg" },
    { code: "MR", name: "Mauritania", phone: "+222", flag: "mauritania.svg" },
    { code: "MS", name: "Montserrat", phone: "+1664", flag: "montserrat.svg" },
    { code: "MT", name: "Malta", phone: "+356", flag: "malta.svg" },
    { code: "MU", name: "Mauritius", phone: "+230", flag: "mauritius.svg" },
    { code: "MV", name: "Maldives", phone: "+960", flag: "maldives.svg" },
    { code: "MW", name: "Malawi", phone: "+265", flag: "malawi.svg" },
    { code: "MX", name: "Mexico", phone: "+52", flag: "mexico.svg" },
    { code: "MY", name: "Malaysia", phone: "+60", flag: "malaysia.svg" },
    { code: "MZ", name: "Mozambique", phone: "+258", flag: "mozambique.svg" },
    { code: "NA", name: "Namibia", phone: "+264", flag: "namibia.svg" },
    { code: "NC", name: "New Caledonia", phone: "+687", flag: "new-caledonia.svg" },
    { code: "NE", name: "Niger", phone: "+227", flag: "niger.svg" },
    { code: "NF", name: "Norfolk Island", phone: "+672", flag: "norfolk-island.svg" },
    { code: "NG", name: "Nigeria", phone: "+234", flag: "nigeria.svg" },
    { code: "NI", name: "Nicaragua", phone: "+505", flag: "nicaragua.svg" },
    { code: "NL", name: "Netherlands", phone: "+31", flag: "netherlands.svg" },
    { code: "NO", name: "Norway", phone: "+47", flag: "norway.svg" },
    { code: "NP", name: "Nepal", phone: "+977", flag: "nepal.svg" },
    { code: "NR", name: "Nauru", phone: "+674", flag: "nauru.svg" },
    { code: "NU", name: "Niue", phone: "+683", flag: "niue.svg" },
    { code: "NZ", name: "New Zealand", phone: "+64", flag: "new-zealand.svg" },
    { code: "OM", name: "Oman", phone: "+968", flag: "oman.svg" },
    { code: "PA", name: "Panama", phone: "+507", flag: "panama.svg" },
    { code: "PE", name: "Peru", phone: "+51", flag: "peru.svg" },
    { code: "PF", name: "French Polynesia", phone: "+689", flag: "french-polynesia.svg" },
    { code: "PG", name: "Papua New Guinea", phone: "+675", flag: "papua-new-guinea.svg" },
    { code: "PH", name: "Philippines", phone: "+63", flag: "philippines.svg" },
    { code: "PK", name: "Pakistan", phone: "+92", flag: "pakistan.svg" },
    { code: "PL", name: "Poland", phone: "+48", flag: "poland.svg" },
    { code: "PM", name: "Saint Pierre and Miquelon", phone: "+508", flag: "saint-pierre-miquelon.svg" },
    { code: "PR", name: "Puerto Rico", phone: "+1787", flag: "puerto-rico.svg" },
    { code: "PS", name: "Palestine", phone: "+970", flag: "palestine.svg" },
    { code: "PT", name: "Portugal", phone: "+351", flag: "portugal.svg" },
    { code: "PW", name: "Palau", phone: "+680", flag: "palau.svg" },
    { code: "PY", name: "Paraguay", phone: "+595", flag: "paraguay.svg" },
    { code: "QA", name: "Qatar", phone: "+974", flag: "qatar.svg" },
    { code: "RE", name: "Réunion", phone: "+262", flag: "reunion.svg" },
    { code: "RO", name: "Romania", phone: "+40", flag: "romania.svg" },
    { code: "RS", name: "Serbia", phone: "+381", flag: "serbia.svg" },
    { code: "RU", name: "Russia", phone: "+7", flag: "russia.svg" },
    { code: "RW", name: "Rwanda", phone: "+250", flag: "rwanda.svg" },
    { code: "SA", name: "Saudi Arabia", phone: "+966", flag: "saudi-arabia.svg" },
    { code: "SB", name: "Solomon Islands", phone: "+677", flag: "solomon-islands.svg" },
    { code: "SC", name: "Seychelles", phone: "+248", flag: "seychelles.svg" },
    { code: "SD", name: "Sudan", phone: "+249", flag: "sudan.svg" },
    { code: "SE", name: "Sweden", phone: "+46", flag: "sweden.svg" },
    { code: "SG", name: "Singapore", phone: "+65", flag: "singapore.svg" },
    { code: "SH", name: "Saint Helena", phone: "+290", flag: "saint-helena.svg" },
    { code: "SI", name: "Slovenia", phone: "+386", flag: "slovenia.svg" },
    { code: "SK", name: "Slovakia", phone: "+421", flag: "slovakia.svg" },
    { code: "SL", name: "Sierra Leone", phone: "+232", flag: "sierra-leone.svg" },
    { code: "SM", name: "San Marino", phone: "+378", flag: "san-marino.svg" },
    { code: "SN", name: "Senegal", phone: "+221", flag: "senegal.svg" },
    { code: "SO", name: "Somalia", phone: "+252", flag: "somalia.svg" },
    { code: "SR", name: "Suriname", phone: "+597", flag: "suriname.svg" },
    { code: "ST", name: "São Tomé and Príncipe", phone: "+239", flag: "sao-tome-principe.svg" },
    { code: "SV", name: "El Salvador", phone: "+503", flag: "el-salvador.svg" },
    { code: "SY", name: "Syria", phone: "+963", flag: "syria.svg" },
    { code: "SZ", name: "Eswatini", phone: "+268", flag: "eswatini.svg" },
    { code: "TC", name: "Turks and Caicos Islands", phone: "+1649", flag: "turks-caicos.svg" },
    { code: "TD", name: "Chad", phone: "+235", flag: "chad.svg" },
    { code: "TG", name: "Togo", phone: "+228", flag: "togo.svg" },
    { code: "TH", name: "Thailand", phone: "+66", flag: "thailand.svg" },
    { code: "TJ", name: "Tajikistan", phone: "+992", flag: "tajikistan.svg" },
    { code: "TK", name: "Tokelau", phone: "+690", flag: "tokelau.svg" },
    { code: "TL", name: "Timor-Leste", phone: "+670", flag: "timor-leste.svg" },
    { code: "TM", name: "Turkmenistan", phone: "+993", flag: "turkmenistan.svg" },
    { code: "TN", name: "Tunisia", phone: "+216", flag: "tunisia.svg" },
    { code: "TO", name: "Tonga", phone: "+676", flag: "tonga.svg" },
    { code: "TR", name: "Turkey", phone: "+90", flag: "turkey.svg" },
    { code: "TT", name: "Trinidad and Tobago", phone: "+1868", flag: "trinidad-tobago.svg" },
    { code: "TV", name: "Tuvalu", phone: "+688", flag: "tuvalu.svg" },
    { code: "TW", name: "Taiwan", phone: "+886", flag: "taiwan.svg" },
    { code: "TZ", name: "Tanzania", phone: "+255", flag: "tanzania.svg" },
    { code: "UA", name: "Ukraine", phone: "+380", flag: "ukraine.svg" },
    { code: "UG", name: "Uganda", phone: "+256", flag: "uganda.svg" },
    { code: "US", name: "United States", phone: "+1", flag: "usa.svg" },
    { code: "UY", name: "Uruguay", phone: "+598", flag: "uruguay.svg" },
    { code: "UZ", name: "Uzbekistan", phone: "+998", flag: "uzbekistan.svg" },
    { code: "VA", name: "Vatican City", phone: "+39", flag: "vatican.svg" },
    { code: "VC", name: "Saint Vincent and the Grenadines", phone: "+1784", flag: "saint-vincent-grenadines.svg" },
    { code: "VE", name: "Venezuela", phone: "+58", flag: "venezuela.svg" },
    { code: "VG", name: "British Virgin Islands", phone: "+1284", flag: "british-virgin-islands.svg" },
    { code: "VI", name: "US Virgin Islands", phone: "+1340", flag: "us-virgin-islands.svg" },
    { code: "VN", name: "Vietnam", phone: "+84", flag: "vietnam.svg" },
    { code: "VU", name: "Vanuatu", phone: "+678", flag: "vanuatu.svg" },
    { code: "WF", name: "Wallis and Futuna", phone: "+681", flag: "wallis-futuna.svg" },
    { code: "WS", name: "Samoa", phone: "+685", flag: "samoa.svg" },
    { code: "YE", name: "Yemen", phone: "+967", flag: "yemen.svg" },
    { code: "YT", name: "Mayotte", phone: "+262", flag: "mayotte.svg" },
    { code: "ZA", name: "South Africa", phone: "+27", flag: "south-africa.svg" },
    { code: "ZM", name: "Zambia", phone: "+260", flag: "zambia.svg" },
    { code: "ZW", name: "Zimbabwe", phone: "+263", flag: "zimbabwe.svg" }
];

export const countriesByPhone = new Map();
export const countriesByCode = new Map();

countries.forEach(country => {
    countriesByCode.set(country.code, country);
    if (!countriesByPhone.has(country.phone)) {
        countriesByPhone.set(country.phone, []);
    }
    countriesByPhone.get(country.phone).push(country);
});